/*
 * Generated by JasperReports
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class GRN_report_65f08a886326a834c38289ff6c601892687dfb58db5aebd6ee3af52f62caa3a7 extends JREvaluator
{


    /**
     *
     */
    private JRFillField field_Qty = null;
    private JRFillField field_Cost_Price = null;
    private JRFillField field_Exp_Date = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_Qty = (JRFillField)fm.get("Qty");
        field_Cost_Price = (JRFillField)fm.get("Cost_Price");
        field_Exp_Date = (JRFillField)fm.get("Exp_Date");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 13 : 
            {
                value = (((java.sql.Date)field_Exp_Date.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 21 : 
            {
                value = Double.valueOf(Double.valueOf(((java.lang.String)field_Qty.getValue())).doubleValue()*Double.valueOf(((java.lang.String)field_Cost_Price.getValue())).doubleValue()); //$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 13 : 
            {
                value = (((java.sql.Date)field_Exp_Date.getOldValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 21 : 
            {
                value = Double.valueOf(Double.valueOf(((java.lang.String)field_Qty.getOldValue())).doubleValue()*Double.valueOf(((java.lang.String)field_Cost_Price.getOldValue())).doubleValue()); //$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 13 : 
            {
                value = (((java.sql.Date)field_Exp_Date.getValue()); //$JR_EXPR_ID=13$
                break;
            }
            case 21 : 
            {
                value = Double.valueOf(Double.valueOf(((java.lang.String)field_Qty.getValue())).doubleValue()*Double.valueOf(((java.lang.String)field_Cost_Price.getValue())).doubleValue()); //$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
